main: net.avallion.admin.AvallionAdmin
name: AvallionAdmin
version: "1.1"
api-version: "1.16"
authors: [GladGladius]
depend: [GladLib]

commands:
  deathstats:
    description: View TPS and ping when a player died.
    permission: avallionadmin.deathstats
    aliases: [dstats, deaths]

permissions:
  avallionadmin.deathstats:
    default: op